volumes:
  postgres_volume_local_chat:

services:
  pg-local-chat:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
        - "${PG_PORT}:5432"
    volumes:
      - postgres_volume_local_chat:/var/lib/postgresql/data

  migrator-local-chat:
    build:
      context: ..
      dockerfile: deploy/migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local-chat

  server-chat:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "50052:50052"
    environment:
      - "PG_USER=${PG_USER}"
      - "PG_PASSWORD=${PG_PASSWORD}"
      - "PG_DATABASE_NAME=${PG_DATABASE_NAME}"
      - "PG_PORT=5432"
      - "PG_HOST=pg-local"
    depends_on:
      - pg-local-chat
      - migrator-local-chat
    volumes:
      - ./server_cert.pem:/server_cert.pem:ro